client/index.ts
client/vertex-client.ts
package-lock.json
package.json

Update links in package.json, add environment information

---

api.ts
base.ts
client/helpers/parts.ts
package.json
spec.yml

[DATA-1259]: Update to latest spec, incorporate breaking changes

---

client/index.ts
client/utils.ts
client/vertex-client.ts
package.json

[API-1358]: Allow setting basePath instead of enviornment

---

client/helpers/parts.ts
package.json

[DATA-1334]: Add delay

---

README.md
api.ts
base.ts
client/index.ts
client/vertex-client.ts
package.json
scripts/generate.sh
spec.yml
yarn.lock

[API-1193]: Update deps and base url to platform.vertexvis.com

---

.gitignore
api.ts
client/helpers/files.ts
client/helpers/parts.ts
client/helpers/scenes.ts
client/utils.ts
client/vertex-client.ts
index.ts
package.json
spec.yml
yarn.lock

Add a `vertexErrorMessage` to `axios` exceptions so they can be easily logged, remove delay.
n/a
n/a

[API-1372]: Update spec to latest, better handle errors

---

.github/workflows/automerge.yml
README.md

[API-1372]: Update README, add automerge

---

client/helpers/files.ts
client/helpers/index.ts
client/helpers/scene-items.ts
client/helpers/scenes.ts
client/vertex-client.ts
package.json
tsconfig.json

[API-1372]: Add scene-item creation, more strict TypeScript flags

---

client/helpers/scenes.ts
package.json
tsconfig.json

[API-1372]: Use `Promise.all` in the client so more node versions are supported

---

api.ts
client/vertex-client.ts
package.json
spec.yml

Update client to include new option for retrieving item overrides.
n/a
n/a

[SDK-1303] Item overrides

---

client/version.ts
client/vertex-client.ts
package.json
scripts/version.sh
yarn.lock

This will automatically update a version file that can be read in by TS and used when setting the user-agent. No need to manually edit versions anymore.
Self tested in this PR.
n/a
n/a

[SDK-1371] Version script

---

api.ts
client/version.ts
package.json
scripts/push_version.sh
spec.yml

[API-1945]: Update to latest spec

---

api.ts
client/utils.ts
client/version.ts
package.json
spec.yml

* Add ability to filter `GET /scenes` by `suppliedId`
* Add ability to set `up` and `front` `worldOrientation` on scene creation and update

[API-1968]: Update to latest spec

---

api.ts
client/helpers/parts.ts
client/helpers/scene-views.ts
client/helpers/scenes.ts
client/index.ts
client/version.ts
package.json
spec.yml
yarn.lock

* Add ability to `PATCH /scenes/:id/scene-view-states`

[API-1994]: Update to latest spec

---

client/utils.ts
client/version.ts
package.json
yarn.lock

[API-2004]: Return self link

---

client/version.ts
package.json

[API-1998]: Release

---

client/helpers/parts.ts
client/helpers/scenes.ts
client/version.ts
package.json
yarn.lock

[API-1997]: Optionally return queued translations/scene-items

---

api.ts
client/version.ts
package.json
spec.yml
yarn.lock

* On scene-view-state creation, thumbnails are generated and returned from `GET /scene-view-states/:id` and `GET /scenes/:id/scene-view-states` if `fields[scene-view-state]=thumbnails` query parameter is included in the request.

[API-2039]: Update to latest spec

---

api.ts
client/version.ts
package.json
spec.yml
yarn.lock

[API-2078]: Update to latest spec

---

client/version.ts
package.json

We need to publish a new version.
Deploy and publish
None
Publishing
None

[ENABLE-1934] Update version

---

client/utils.ts
client/version.ts
package.json
yarn.lock

[API-2222]: Export VertexError

---

.eslintrc.js
api.ts
client/helpers/files.ts
client/helpers/parts.ts
client/helpers/queued-jobs.ts
client/helpers/scene-views.ts
client/helpers/scenes.ts
client/utils.ts
client/version.ts
client/vertex-client.ts
package.json
scripts/generate.sh
spec.yml
verify.ts
yarn.lock

[API-2237]: Fix pollQueuedJob

---

api.ts
base.ts
client/helpers/parts.ts
client/helpers/queued-jobs.ts
client/helpers/scenes.ts
client/utils.ts
client/version.ts
package.json
scripts/generate.sh
spec.yml
tsconfig.json
typedoc.json
yarn.lock

[API-2237]: Add experimental support for /batches, fix doc warnings

---

api.ts
client/helpers/scenes.ts
client/version.ts
client/vertex-client.ts
package.json
spec.yml

[API-2261]: Add accounts and applications, increase batch size

---

.gitignore
api.ts
client/helpers/files.ts
client/version.ts
package.json
spec.yml
yarn.lock

Axios has a number of issues both opened and closed relating to file uploads and streams in general. I read through each one and tried a number of things, including setting [`maxRedirects: 0` to prevent streams from being pulled into memory](https://github.com/axios/axios/issues/1045) and [setting a dummy `transformRequest` that just returned the data untransformed](https://github.com/axios/axios/issues/1250). I tried this with and without streams, uploading 175 files of varying sizes (from 19kb to 10MB). Each resulting in a small minority of files uploaded with different sizes than they are known to have.
Adding the `Content-Length` header doesn't work for streams, [as this issue suggests it might](https://github.com/axios/axios/issues/961). However, using `readFileSync` along with …

[API-2238] Pass file size and use Buffer over Stream for file uploads

---

client/helpers/files.ts
client/version.ts
package.json

[API-2238] Accept filePath to ensure it's opened properly

---

client/helpers/files.ts
client/helpers/parts.ts
client/version.ts
client/vertex-client.ts
package.json

[API-2238] Bypass axios if requested

---

client/utils.ts
client/version.ts
package.json

[PLAT-104] Better errors

---

package.json

[PLAT-267] bump version

---

api.ts
client/helpers/exports.ts
client/helpers/index.ts
client/version.ts
client/vertex-client.ts
package.json
spec.yml

New resources for creating and getting exports from the platform.

[PLAT-1074] Export Endpoints

---

api.ts
client/version.ts
package.json
spec.yml

[PLAT-1327] Bump version to include name for export

---

api.ts
client/version.ts
package.json
spec.yml

TSIA
This includes some changes that aren't mine, but are just for docs. Also, the version got updated to 0.18.1 instead of 0.18.0, because of some reasons. I figure it's not a big deal.

PLAT-1642: update to latest API

---

api.ts
client/helpers/parts.ts
client/version.ts
package.json
spec.yml

Latest vertex-api spec changes

[PLAT-1699] Latest Release

---

api.ts
client/helpers/queued-jobs.ts
client/helpers/scenes.ts
client/version.ts
package.json
scripts/push_version.sh
spec.yml

- v0.20.3
- Introduced staged scene item creation to experimental scene creation strategy
- Update to latest API spec
- Update to latest API spec
- Updated experimental scene creation strategy to create scene items in stages
- These changes should only impact the experimental option for scene creation

[PLAT-2038]: Latest API Spec + Updated Experimental Scene Creation Strategy

---

api.ts
client/version.ts
package.json
spec.yml

[PLAT-2230] Latest Vertex API spec

---

api.ts
spec.yml

Update the client to the latest spec which includes the ability to create an Assembly from existing PartRevisions
[Vertex-API](https://github.com/Vertexvis/vertex-api/pull/402)

[PLAT-2411] -- Create assemblies from part revs 

---

api.ts
client/version.ts
package.json
spec.yml

[PLAT-2396] Perspective Camera FovY Support

---

api.ts
spec.yml

[PLAT-2638] Bumping Version

---

api.ts
client/version.ts
package.json
spec.yml

This pulls in the latest from vertex-api. This includes adding revision name when creating the part and also the new QueuedTranslationJob API
Test using a client like plm-integration-service
None
None expected

[PLAT-2727] pull revision name

---

.gitignore
README.md
api.ts
client/version.ts
package.json
spec.yml

[PLAT-2601] Latest API Spec

---

api.ts
client/version.ts
package.json
spec.yml

TSIA
https://vertexvis.atlassian.net/browse/PLAT-2602

[PLAT-2602] Add option to filter scenes by metadata

---

api.ts
base.ts
client/helpers/index.ts
client/helpers/queued-jobs.ts
client/index.ts
client/utils.ts
client/version.ts
index.ts
package.json
spec.yml
yarn.lock

We want to update the API-client-node library to use latest version of Axios.
Verify the service successfully deploys and publishes
None
Building and publishing service
None

[PLAT-3310] Update axios

---

api.ts
base.ts
client/helpers/scenes.ts
client/version.ts
common.ts
configuration.ts
package.json
spec.yml

- Exposed `createSceneItemBatch` helper method for use by consumers.
- Reduced default batch size for scene item creation to address intermittent payload size problems
- Updated to latest API spec

PLAT-3644: Allow public use of createSceneItemBatch method

---

api.ts
client/helpers/parts.ts
client/helpers/queued-jobs.ts
client/version.ts
package.json
spec.yml

[PLAT-4024] Fixing queued jobs and bumping version

---

client/version.ts
client/vertex-client.ts
package.json

Exposes the scene annotations api on the client.
https://vertexvis.atlassian.net/browse/PLAT-4141

[PLAT-4141] Expose scene annotations API

---

api.ts
client/version.ts
package.json
spec.yml

Updates to the latest spec to include support for listing `SceneAnnotationSet`s.

[PLAT-4472] Support SceneAnnotationSet listing

---

client/version.ts
package.json

Publishes v0.23.2, which includes updates to the error messages when a job fails or times out.

[PLAT-4707] Publish v0.23.2

---

api.ts
client/helpers/parts.ts
client/utils.ts
client/version.ts
package.json
scripts/push_version.sh
spec.yml

This addedc the supplied Iteration Id to the part revision.
Good way to test this is using dev-dashboard
None. Should be published in the OpenAPI spec.
None expected
None

[PLAT-5255] Added supplied iteration Id

---

api.ts
client/version.ts
package.json
spec.yml

https://vertexvis.atlassian.net/browse/PLAT-5961

[PLAT-5961] Include new flag to create stream key with search session

---

api.ts
client/version.ts
package.json
scripts/generate.sh
scripts/push_version.sh
spec.yml

- **v0.25.0**
- **v0.26.0**
- **Update to latest spec**

[PLAT-5858-FILE-COLLECTIONS]: Update to latest spec

---

api.ts
client/version.ts
package.json
scripts/generate.sh
spec.yml

Updated to latest API spec which includes addition of File Jobs API.

Update to latest API spec (PLAT-6363)

---

api.ts
client/version.ts
package.json
spec.yml

- **v0.30.3**
- **Update to latest spec**
[Ticket](https://vertexvis.atlassian.net/browse/PLAT-6805)

[PLAT-6805]: Update to latest spec

---

api.ts
client/version.ts
package.json
scripts/generate.sh
scripts/push_version.sh
scripts/utils.sh
spec.yml

- **v0.31.0**
- **Update to latest spec**
- Added `sed_inplace()` shell function to work around non-portable `sed` invocations

[PLAT-6898]: Update to latest spec

---

api.ts
client/version.ts
client/vertex-client.ts
package.json
scripts/push_version.sh
spec.yml

* **v0.32.0**
* **Update to latest spec**
Additionally, this adds `collaborationContexts` and `users` to the `VertexClient`, but intentionally omits `replies` and `threads`, as those will require a different token to interact with (@danschultz or @mcallydevelops let me know if we do actually want to add these here).

[PLAT-6922]: Update to latest spec
